
stages:
  - build

build:client:web:
  image: docker pull cirrusci/flutter:dev
  stage: build
  script:
    - "cd client"
    - "flutter doctor -v"
    - "flutter build web"
  artifacts:
    paths:
      - "client/build/web/*"
    expire_in: never

build:server:mac:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  script:
    - "cd server"
    - "rustc --version && cargo --version"
    - "rm -rf target"
    - "CC=o64-clang CXX=o64-clang++ cargo build --release --target=x86_64-apple-darwin"
    - "cp target/x86_64-apple-darwin/release/{kiln_server,kiln_tools} ../"
  artifacts:
    paths:
      - "kiln_server"
      - "kiln_tools"
    expire_in: never

build:server:linux:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  script:
    - "cd server"
    - "rustc --version && cargo --version"
    - "rm -rf target"
    - "cargo build --release --target=x86_64-unknown-linux-musl"
    - "cp target/x86_64-unknown-linux-musl/release/{kiln_server,kiln_tools} ../"
  artifacts:
    paths:
      - "kiln_server"
      - "kiln_tools"
    expire_in: never
