# # Cache downloaded dependencies and plugins between builds.
# # To keep cache across branches add 'key: "$CI_JOB_NAME"'
# cache:
#   paths:
#     - etech_client/node_modules

stages:
  - build

# # webpack build stage
# build:webpack:
#   image: node:latest
#   stage: build
#   script:
#     - "cd hub_client"
#     - "npm i"
#     - "npm run build"
#   artifacts:
#     paths:
#       - "hub_client/dist/*"
#       - "hub_server/target/x86_64-unknown-linux-musl/release/hub_server"
#     expire_in: never

# cargo build stage
build:server:mac:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  script:
    - "cd server"
    - "rustc --version && cargo --version"
    - "rm -rf target"
    - "CC=o64-clang CXX=o64-clang++ cargo build --release --target=x86_64-apple-darwin"
  artifacts:
    paths:
      - "server/target/x86_64-apple-darwin/release/kiln_server"
      - "server/target/x86_64-apple-darwin/release/kiln_tools"
    expire_in: never

build:server:linux:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  script:
    - "cd server"
    - "rustc --version && cargo --version"
    - "rm -rf target"
    - "cargo build --release --target=x86_64-unknown-linux-musl"
    - "cp server/target/x86_64-unknown-linux-musl/release/{kiln_server,kiln_tools} ../"
  artifacts:
    paths:
      - "kiln_server"
      - "kiln_tools"
    expire_in: never
