
stages:
  - build

build:client:web:
  image: cirrusci/flutter:dev
  stage: build
  script:
    - "cd client"
    - "flutter doctor -v"
    - "flutter build web"
    - "cp -r build/web .."
  artifacts:
    paths:
      - "web/*"
    expire_in: never

build:client:apk:
  image: cirrusci/flutter:dev
  stage: build
  script:
    - "cd client"
    - "flutter doctor -v"
    - "flutter build apk"
    - "cp build/app/outputs/apk/release/app-release.apk ../kiln-controller.apk"
  artifacts:
    paths:
      - "kiln-controller.apk"
    expire_in: never

build:client:appbundle:
  image: cirrusci/flutter:dev
  stage: build
  script:
    - "cd client"
    - "flutter doctor -v"
    - "flutter build appbundle"
    - "cp build/app/outputs/bundle/release/app-release.aab ../kiln-controller.aab"
  artifacts:
    paths:
      - "kiln-controller.aab"
    expire_in: never

build:client:linux:
  image: cirrusci/flutter:dev
  stage: build
  script:
    - "cd client"
    - "flutter config --enable-windows-desktop"
    - "flutter config --enable-windows-uwp-desktop"
    - "flutter config --enable-macos-desktop"
    - "flutter config --enable-linux-desktop"
    - "flutter doctor -v"
    - "flutter build"
  # artifacts:
  #   paths:
  #     - "kiln-controller.apk"
  #   expire_in: never

build:server:mac:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  script:
    - "cd server"
    - "rustc --version && cargo --version"
    - "rm -rf target"
    - "CC=o64-clang CXX=o64-clang++ cargo build --release --target=x86_64-apple-darwin"
    - "cp target/x86_64-apple-darwin/release/{kiln_server,kiln_tools} ../"
  artifacts:
    paths:
      - "kiln_server"
      - "kiln_tools"
    expire_in: never

build:server:linux:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  script:
    - "cd server"
    - "rustc --version && cargo --version"
    - "rm -rf target"
    - "cargo build --release --target=x86_64-unknown-linux-musl"
    - "cp target/x86_64-unknown-linux-musl/release/{kiln_server,kiln_tools} ../"
  artifacts:
    paths:
      - "kiln_server"
      - "kiln_tools"
    expire_in: never
